name: Mumble
main: me.Clarkcj.mumble.Mumble
version: 1.1
author: Clarkcj
description: >
             Mumble Plugin.
commands:
  mumble:
    description: Sends mumble information
  mumbleinfo:
    description: Sends user mumble info
