name: VoicePlus
main: me.Clarkcj.voiceplus.VoicePlus
version: 1.7.2 Beta

author: Clarkcj
description: >
            A Plugin that a player to find out what the mumble and teamspeak info is.
commands:
  mumble:
    description: Sends Mumble Download Link
  mumbleinfo:
    description: Sends Mumble Server Info
  teamspeak:
    description: Sends TeamSpeak Download Link
  teamspeakinfo:
    description: Sends TeamSpeak Server Info
