name: VoicePlus
main: us.mcthemeparks.VoicePlus
version: mvn-version
authors: [Clarkcj, willies952002]

description: Tells The Players What the Server's Voice Server Address is.
commands:
  teamspeakinfo:
    description: Sends TeamSpeak Information
    aliases: tsinfo
    usage: /<command>
  mumbleinfo:
    description: Sends Mumble Information
    aliases: minfo
    usage: /<command>
  voiceplus:
    description: Sends Mumble Download Link
    aliases: mumble
    usage: /<command>
  teamspeak:
    description: Sends Teamspeak Download Link
    aliases: ts
    usage: /<command>
  DiscordInvite:
    descirption: Sends Discord Invite Link
    usage: /<command>
  Discord:
    description: Sends Link About Discord
    usage: /<command>